
services:
  
  mysql:
    image: mysql:8.4
    container_name: mysql-punto-venta

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: punto_venta
      MYSQL_USER: puntoventa
      MYSQL_PASSWORD: PuntoVenta_2026!

    ports:
      - "3307:3306"

    volumes:
      - mysql_data:/var/lib/mysql
  api:
    build: .
    container_name: api-punto-venta

    restart: unless-stopped

    depends_on:
      - mysql

    ports:
      - "8081:8081"

    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
volumes:
  mysql_data:

