
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/punto_venta?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${DB_USERNAME:puntoventa}
spring.datasource.password=${DB_PASSWORD:PuntoVenta_2026!}

spring.jpa.show-sql=false

server.address=0.0.0.0
server.port=8081

app.api.url=https://apijavadocker.mabcontrol.ar

jwt.secret=${JWT_SECRET:CursoJava26PuntoVentaSecretKeyParaHS256Minimo256Bits==}
